const projectDetails = [
  {
    id: 6,
    img: "./Projects/talkbot.png",
    projectName: "Talkbot",
    desc: "A conversational AI app inspired by OpenAI's GPT-3",
    techStack: [
      "React",
      "React Router",
      "Open AI API",
      "Firebase",
      "Node JS  ",
    ],
    viewLive: "https://talk-bot.netlify.app/",
    githubLink: "https://github.com/dhiant/react-chatGPT-clone/",
  },
  {
    id: 1,
    img: "./Projects/hotel_enroll.png",
    projectName: "Hotel Enroll",
    desc: "An advanced hotel booking site",
    techStack: ["React", "Tailwind CSS", "Swiper JS", "React Icons"],
    viewLive: "https://hotelenroll.netlify.app/",
    githubLink: "https://github.com/dhiant/online_booking_system",
  },
  {
    id: 2,
    img: "./Projects/marvel_movies.png",
    projectName: "Marvel Movies",
    desc: "A movie app to watch MCU movies chronologically",
    techStack: ["React", "Tailwind CSS", "CSS Animation"],
    viewLive: "https://marvelsushant.netlify.app/",
    githubLink: "https://github.com/dhiant/marvel-movies",
  },
  {
    id: 3,
    img: "./Projects/feedback_app.png",
    projectName: "Feedback App",
    desc: "",
    techStack: ["React", "Tailwind CSS", "Framer Motion", "React Icons"],
    viewLive: "https://feedbackapp-reactjs.netlify.app/",
    githubLink: "https://github.com/dhiant/react-feedback-app",
  },
  // {
  //   id: 4,
  //   img: "./Projects/staff_book.png",
  //   projectName: "Staff Book",
  //   desc: "An employee record keeping app",
  //   techStack: ["React", "Tailwind CSS", "React Router"],
  //   viewLive: "https://mystaffbook.netlify.app/",
  //   githubLink: "https://github.com/dhiant/react-context/tree/crud-app",
  // },
  {
    id: 5,
    img: "./Projects/wondermall.png",
    projectName: "Wondermall",
    desc: "A complete e-commerce site",
    techStack: ["React", "Redux", "Material UI", "Firebase", "Axios"],
    viewLive: "",
    githubLink: "https://github.com/dhiant/learn-redux",
  },
];

export default projectDetails;
