const projectDetails = [
  {
    id: 1,
    img: "./Projects/talkbot.png",
    projectName: "Talkbot",
    desc: "A conversational AI app inspired by OpenAI's GPT-3",
    techStack: [
      "React",
      "React Router",
      "Open AI API",
      "Firebase",
      "Node JS  ",
    ],
    viewLive: "https://talk-bot.netlify.app/",
    githubLink: "https://github.com/dhiant/react-chatGPT-clone/",
  },
  {
    id: 2,
    img: "./Projects/hotel_enroll.png",
    projectName: "Hotel Enroll",
    desc: "An advanced hotel booking site",
    techStack: ["React", "Tailwind CSS", "Swiper JS", "React Icons"],
    viewLive: "https://hotelenroll.netlify.app/",
    githubLink: "https://github.com/dhiant/react-hotel-enroll",
  },
  {
    id: 3,
    img: "./Projects/marvel_movies.png",
    projectName: "Marvel Movies",
    desc: "A movie app to watch MCU movies chronologically",
    techStack: ["React", "Tailwind CSS", "CSS Animation"],
    viewLive: "https://marvelsushant.netlify.app/",
    githubLink: "https://github.com/dhiant/marvel-movies",
  },
  {
    id: 4,
    img: "./Projects/medcare-hospital.png",
    projectName: "Medcare",
    desc: "Hospital Website",
    techStack: ["React", "Tailwind CSS", "Swiper JS","React Leaflet"],
    viewLive: "https://react-medcare.netlify.app/",
    githubLink: "https://github.com/dhiant/react-medcare",
  },

  {
    id: 5,
    img: "./Projects/wondermall.png",
    projectName: "Wondermall",
    desc: "A complete e-commerce site",
    techStack: ["React", "Redux", "Material UI", "Firebase", "Axios"],
    viewLive: "https://wondermall.netlify.app/",
    githubLink: "https://github.com/dhiant/wondermall",
  },
  {
    id: 6,
    img: "./Projects/supreme-fitness.png",
    projectName: "Ultimate Fitness",
    desc: "Fitness Website made with Wordpress",
    techStack: ["HTML", "CSS", "Wordpress Plugin", "Wordpress Theme"],
    viewLive: "https://supreme-fitness.netlify.app/",
    githubLink: "https://github.com/dhiant/wordpress-fitness-website",
  },
  {
    id: 7,
    img: "./Projects/trackify.png",
    projectName: "MeloTunes",
    desc: "Music App inspired by Spotify",
    techStack: ["React", "Tailwind CSS", "React Content Loader", "Axios","Swiper JS"],
    viewLive: "https://melotunes.netlify.app/",
    githubLink: "https://github.com/dhiant/react-melotunes",
  },
  {
    id: 8,
    img: "./Projects/steve-jobs.png",
    projectName: "Steve Jobs",
    desc: "Tribute Page of Steve Jobs",
    techStack: ["HTML", "Vanilla CSS",],
    viewLive: "https://stevenjobs.netlify.app/",
    githubLink: "https://github.com/dhiant/steve.github.io",
  },
];

export default projectDetails;
